name: flutter_appandme_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo.png
    - assets/img/logo2.png
    - assets/img/maker_fair1.png
    - assets/img/maker_fair2.png
    - assets/img/study1.png
    - assets/img/study2.png
    - assets/img/networking1.png
    - assets/img/networking2.png
    - assets/img/instagram.png
    - assets/img/github.png
